version: '3.8'

services:
  rstudio:
    image: rocker/rstudio
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=${PASSWORD}
    volumes:
      - ./config:/home/rstudio/config
      - ./projects:/home/rstudio/projects
